### ISSUE TITLE
[meta] Settings Re-org

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1205]
Creating a meta bug to collect and address a whole bunch of issues in Settings in one go. The biggest is to re-organize the Settings menu to be easier to use.

- [x] #834 Explain blocking settings better
- [x] #1054 Default browser option is buried
- [x] Fix string capitalization (needs issue created)
- [x] Ensure stealth mode is clear (potentially needs issue)
- [ ] change default browser from toggle to ? (perhaps like opera mini). also make string more androidy
- [x] #1294 Clarify "Mozilla" grouping in Settings

**Comment by ekager** [comment]
Hey @brampitoyo after #2357 , can this issue and #1294 be closed? Or is there more that we want to break down from this to include in the future?

**Comment by brampitoyo** [comment]
@ekager Sorry for the confusion! After #2357 is completed, this issue and #1294 can be closed.

**Comment by ekager** [comment]
Closed by #2590
