### ISSUE TITLE
Implement focus-internal locale switching

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#122]
**Theme:** _Default Browser_

**User Story**

> As a user I want to switch the language in Focus

**Background**

Similar to what Fennec does: we could potentially implement our own locale switching, to allow overriding the OS locale. (Firefox supports more locales than Android does, you can read more about what fennec does in https://160.twinql.com/new-locale-related-work-in-firefox-for-android/ )

See fennec bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=936756
https://bugzilla.mozilla.org/show_bug.cgi?id=917480

This seems quite complicated, so I'm guessing we won't want this in v1 - but it might be nice to have in future.

**Tasks**

- [x] Extract code from Fennec (Optionally create separate library)
- [x] Integrate locale switching into Fennec
- [x] UX mocks / flow
- [x] Ensure WebView sends correct Accept-Language headers
- [x] Add settings UI for switching language (Mirror System vs. List of shipping languages)
- [x] Add telemetry probes?

**Things to test**

- [x] Switching system language works: (A) locale changes correctly if using system language, (B) locale doesn't change if using custom language
- [x]  RTL switches work (including for the previous case)
- [x] Other config changes don't break things
- [x] Locale switches while in background (see comments in LocaleAwareApplication.onConfigurationChanged()).

**Comment by pocmo** [comment]
Yeah, definitely not v1. :)

**Comment by pocmo** [comment]
Fennec docs:
https://gecko.readthedocs.io/en/latest/mobile/android/fennec/localeswitching.html

**Comment by rprys** [comment]
If it's Mozilla's intention to enable the public to use the Web safely, avoiding it's pitfalls, then this needs to be in at v.1.
Google has taken upon its self to divide the haves and have nots with language support in Android. Not including this technology may be easier in terms of packaging and download size but it's not useful for Mozilla's credibility. 
Less resourced languages, thanks to the likes of Google have less resources. That means they have less in the way of information to guide speaker in being safe and cautious on the internet and as a result more open to abuse. Is this what Mozilla wishes to foster? Those who have less, get less support and guidance? I don't think so.
Less resourced languages need Firefox Focus more than well resourced languages.
So please, Mozilla has the technology, the expertise, and the translation support to develop Firefox Focus for Android for all languages from the off. We can also do difficult things ;-)
Let's do it.

**Comment by ahunt** [comment]
@antlam What do we want the UX selection to lookg like? Here's what I've currently got for testing:
![settings](https://cloud.githubusercontent.com/assets/1546915/26081806/6cc4260a-3981-11e7-886d-c38cdce23dff.png)
![selector](https://cloud.githubusercontent.com/assets/1546915/26081818/72dfb874-3981-11e7-865d-ea2a0eff3056.png)

(Note: the language codes will be replaced with readable languages eventually, I'm just using that list for testing.)

**Comment by antlam** [comment]
This looks mostly like our Fennec UI currently. I think it looks fine. 

But we should probably keep consistent with the casing and use "System default" rather than "System Default" :)

**Comment by ahunt** [comment]
One known bug (which Firefox also exhibits), is that the locale doesn't change (until app restart) if you:
1. Start with Focus using a custom locale (i.e. not system default). (Force-kill the app after setting a custom locale)
2. Set to system default -> language updates
3. Change the OS locale, return to Focus -> language doesn't change (but should reflect the new system locale)

If Focus is already set to "system default", and the OS language is changed, then we correctly update the language. This issue only occurs if Focus was started with a custom locale.

**Comment by ahunt** [comment]
I'd also like to move this into a library eventually, however that's probably beyond the scope of Focus v1. LocaleSwitchPreference should be moved into org.mozilla.focus.locales, we can then move all of that package into a library.

That would require some opinions on:
1) Settings screen triggering (since we go through LocaleAwareActivity for that).
2) Locale list

A "LocaleHelper" which provides settings screen and locale list callbacks (that the app must implement) might be simplest.

**Comment by ahunt** [comment]
We already send telemetry automatically when changing settings (pref_locale), so we probably don't need to add anything else for that.

**Comment by pocmo** [comment]
Afaik we only send telemetry for preferences listed in TelemetryWrapper (setPreferencesImportantForTelemetry) - Can you add this to telemetry.md too?

**Comment by ahunt** [comment]
Huh, I saw "pref_locale" in the following query - I'll try to see why we're sending "unimportant" prefs:
https://sql.telemetry.mozilla.org/queries/4672

**Comment by pocmo** [comment]
Oh, yeah, that's confusing. We are sending "change" event telemetry for all preferences. But there's also the option to send the current state of preferences as part of *every* event ping: https://github.com/mozilla-mobile/focus-android/blob/master/docs/telemetry.md#settings

This allows us to determine the current state of the setting without the need to know about all changes.
