### ISSUE TITLE
[meta] Erase interaction improvements V2

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1312]
UX meta to track related issues. No milestone attachment necessary.

- [x] Possible A11y concerns with the Erase FAB
- [x] Handle more robust Erasing use-cases 
- [x] Tapability concerns with placement of FAB (#3201)
- [x] #809 
- [x] #810
- [x] #467
- [x] See the referenced issues below and add them if relevant

**Comment by layely** [comment]
@antlam I would handle this ==> Add confirmation before clearing browsing history due to back button #1295

**Comment by antlam** [comment]
@layely will keep that in mind! Just an FYI, we're still prioritizing this stuff :)

**Comment by Benestar** [comment]
Related to #467 - I think the `undo` option would be preferable to a confirmation dialog.

**Comment by antlam** [comment]
@Benestar 'undo' is difficult because of many reasons. So we'll have to be careful about thinking this through, especially for a product like Focus.

To start, it implies we have to "save" user data so that we can restore it for them. From there, we have to save the trail of navigation too so that backwards and forwards would work.

**Comment by Benestar** [comment]
I take it as @pocmo already wrote

> In theory it's super easy: Keep the fragment around and if the user pressed undo then re-attach it. 

Apparently there are some Android related issues but by just delaying the destruction of the browsing fragment for a few seconds I think we could handle the undo without explicitly storing the current state of the browser.

**Comment by antlam** [comment]
Yes, I have also talked to @pocmo about this and we've had discussions too.

While the technical side is just the start (as I mentioned), we should still make sure we think through all the messaging and experience implications before we proceed.

**Comment by pocmo** [comment]
> I take it as @pocmo already wrote
>>    In theory it's super easy: Keep the fragment around and if the user pressed undo then re-attach it.

The situation has changed a bit since then. We have multiple tabs now. Instead of keeping the fragment around we'd want to keep the `Session` object around. This might allow us to restore the session - cookies, cache etc. would be deleted already though.

**Comment by bbinto** [comment]
More GPS comments

"There is one big design flaw that stupid delete and exit button that sits 
in the bottom right hand corner. It's way too easy to accidentally tap it 
and uninentionally causing you to loose your work . This has happened just 
after exit from the onscreen keyboard. Why is this not an option I can turn 
off. What idiot designer thinks floating buttons are a good idea why can't 
we stick with have choice to stick to standard menu options. Deducting 3 
stars for user frustration."
