### ISSUE TITLE
[meta] Extract Fennec Switchboard into Reuseable Library

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#1431]
Let's actually do what @pocmo suggested: https://github.com/mozilla-mobile/focus-android/issues/1030#issuecomment-318631760

Assigning to @liuche for now, may change.

----

### Tasks:

* [x] #1494 - Breakdown bug

#### Must-have
* [ ] #1574 - Finalize and test Kinto configuration/admin for server-side configuration of experiments
* [ ] #1575 - Create separate repository and minimal CI environment for library
* [ ] #1576 - Implement client for loading (partial) experiment configuration from server
* [ ] #1577 - Implement storage for saving experiment configuration to disk 
* [ ] #1589 - Schedule frequent updates of experiments configuration 
* [ ] #1578 - Implement code for evaluating experiment configuration and bucketing users 
* [ ] #1579 - Implement simple API for checking if an installation is part of a specific experiment
* [ ] #1580 - Deploy experiments library to jcenter
* [ ] #1581 - Integrate experiments library into Focus
* [ ] #1588 - Add experiments to core ping 
* [ ] #1587 - Documentation and guides 

#### Nice-to-have / Improvements
* #1582 - Implement simple API for getting experiment metadata
* #1583 - Verify signatures of experiments collection
* #1584 - Add mechanism for overriding the local experiment configuration
* #1585 - Add developer/debug UI for setting experiment overrides
* #1586 - Certificate pinning

**Comment by pocmo** [comment]
There are two things that I was planning to do here additionally:
* Rename the library. "Switchboard" was the name of the library we used in Fennec. However since then a lot has changed and the framework now works differently. So I think we should use a new name to reflect that (My favorite is "Fretboard" 😝 - But that's up to whoever does the work here, I guess)
* Some of the Switchboard code in Fennec is not really high quality. As part of moving this to a separate library I wanted to clean this up. Maybe even convert/re-write this in Kotlin.

**Comment by liuche** [comment]
@bbinto considers this high-priority for the next couple of months - let's put this into Granite and then decide the tradeoffs.

**Comment by pocmo** [comment]
Tasks updated.

**Comment by Sdaswani** [comment]
Great example of a breakdown @pocmo . At the end of all this work, what capabilities will be enabled from a 'marketing platform' point of view? For example, what features mentioned [here](https://www.leanplum.com/platform/mobile-ab-testing-optimization/) would be covered by this work, or all the work intended to build this A/B testing framework?

I think these are important questions to answer as starting on this work takes a lot of effort away from building features.

**Comment by pocmo** [comment]
@Sdaswani 

The things in the must-have list give us:

* A way to configure experiments on the server-side using the Kinto admin web interface.
* Experiments can be enabled for a subset of users:
  * percentage (in 1% steps)
  * package name (to target specific builds like dev or beta builds)
  * version
  * language
  * country (from locale)
  * device ("Only Pixel devices")
  * manufacturer ("Only Google devices")
  * (In Fennec we can also filter by GeoIP country, I omitted this here, because it needs access to a second web service, but we can add this later if needed)
* On app-side we can trigger specific code paths depending on whether a user is part of a specific experiments
* Experiments the user is enrolled in are added to the core ping - so we can use all our telemetry tools to evaluate experiments.
* Experiments can have additional payload data that can be used to configure an experiment. For example if we wanted to limit the number of tabs a user can open then we could attach this number to an experiment and change it on the fly. (I categorized this as "Nice-to-have" as we might not need this for the first set of simple experiments).
* The configuration of experiments is pulled from our servers regularly. The protocol allows only pulling diffs so that not much bandwidth is needed.
* All evaluation of the configuration is happening on the client side! This means that no identifiers etc. need to be send to a server. 

We have been using this for quite a while in Fennec to do A/B experiments and staged roll out of features (or pulling them in an "emergency").

The breakdown above covers the work to get this functionality out of Fennec into its own library - so that it can be used by Focus and other future apps. This means that some of the "Implement X" issues actually mean "Take this from Fennec, clean it up and remove dependencies on Fennec". The switchboard code we imported into Fennec some time ago wasn't particularly nice - so I would like to clean that up - maybe even convert it to Kotlin.

Wiki page describing the integration in Fennec:
https://wiki.mozilla.org/Mobile/Fennec/Android/Switchboard

Example configuration for Fennec:
https://firefox.settings.services.mozilla.com/v1/buckets/fennec/collections/experiments/records

**Comment by Sdaswani** [comment]
Thanks @pocmo , this is great. I'm meeting with @bbinto, @lime124 and @antlam next week to understand exactly what we want for A/B testing, so we understand how well the different options support them.

**Comment by bbinto** [comment]
Leaving this here for now.

First and most important use cases for using an A/B framework:
- Talk to our users more and quicker: show survey invite/link to specific group of users
- Iterate faster and improve 1D retention via onboarding experiments (e.g. removing/adding first run slides, showing contextual hints)
- Nice to have: Changes to labels, e.g. change Menu label "Add to homescreen" to "Save to homescreen" etc.

We are currently not interested in any other in-product marketing such as push notifications.

**Comment by antlam** [comment]
I think we should probably try out the Visual UI Editor and the Rich Survey tool to be sure. :)

I haven't tried the Rich Survey tool yet, but it could be a good way to for us to get those reviews we've been dreaming about. I do have some questions though because it seems to oversimplify the UI design side of things. For example, could we set _no_ background image? 

In terms of the Visual UI Editor, from my experience working with it, it can be quite inflexible... For example (I know that article was written in 2015 but), one of the feature updates that are listed is "changing text" and in the screenshot I remember only being able to change size and color. I don't think we can change the font type. That _might be OK_ if the font is just the system fonts though (Roboto, SF).

**Comment by Sdaswani** [comment]
Cool, let me plug in the latest SDK and give a demo of what it can do.

**Comment by Sdaswani** [comment]
@pocmo does the world you've broken down include the items @bbinto listed [here](https://github.com/mozilla-mobile/focus-android/issues/1431#issuecomment-342180890)? If not, how much do you think it would add to the up front dev cost?

FYI @bbinto i think your requirement for general A/B testing is confirmed [here](https://github.com/mozilla-mobile/focus-android/issues/1431#issuecomment-341429860).

**Comment by pocmo** [comment]
> @pocmo does the world you've broken down include the items @bbinto listed here? If not, how much do you think it would add to the up front dev cost?

We should have the capabilities to run those experiments. Some of them might need additionally UX/code that we enable in an experiment though. I suggest filing separate issues for them so that we can prioritize and plan them.

> Talk to our users more and quicker: show survey invite/link to specific group of users

Definitely possible - we'd have to decide how those links invites should show up though.

> Iterate faster and improve 1D retention via onboarding experiments (e.g. removing/adding first run slides, showing contextual hints)

As discussed onboarding is a special case because it is usually shown *before* we had the chance to talk to a server. In Fennec we have been shipping the configuration for those experiments in the app so that they have been available immediately. Another option would be to at least wait some seconds for the configuration to arrive and only run an onboarding experiment if we get it fast enough. Anyhow, all the reporting etc. does not need to be changed. Of course we'd need to definite what those onboarding slides / experiments should look like.

> Nice to have: Changes to labels, e.g. change Menu label "Add to homescreen" to "Save to homescreen" etc.

Yeah, that's something that we could do easily. L10N can be tricky - or we could decide to run this experiment for English users only.

**Comment by Sdaswani** [comment]
> Another option would be to at least wait some seconds for the configuration to arrive and only run an onboarding experiment if we get it fast enough.

Yes, it would be nice if we improve this when we undergo this effort.

> we could decide to run this experiment for English users only.

Also yes, English is our biggest user base by far (~30% on Android), so restricting to us will still give us statistically significant results.

**Comment by pocmo** [comment]
Closing this (and the subtasks) as we are tracking this work outside of Focus:
* https://github.com/mozilla-mobile/fretboard
* https://github.com/mozilla-mobile/fretboard/projects/1

For Focus we still have: #2350
