### ISSUE TITLE
[meta]Add feature flags

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1515]
### Eng
* [ ] #1548 eng breakdown
* [ ] Constants file to toggle features on/off
* [ ] Config file to control constants' definition/state, and a way to preprocess the Constants file
* [ ] Hook into build system to enable flags (for specific builds, like release, beta?, dev builds, l10n screenshots) for automation

### UX
* [ ] #1550 ux breakdown
----
We want to add the ability to turn on/off features based on feature flags so that we can
1) incrementally land features that may not be complete
2) allow predictable feature releases

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by liuche** [comment]
Feature flags are for developers to hold features back, but at the moment we don't have a pressing need or feature that needs a flag right now.

We're putting this into a P3 for now.
