### ISSUE TITLE
[meta] Rethink/refactor our erase strategy

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1569]
Quick breakdown, but we should do more in #1822.
- [x] #1822: breakdown
- [ ] #2012 Document high-level goals for erasing
- [ ] #1472 Is erasing WebView files a good idea?
- [x] #2013 High-level understanding: summarize all the ways the browsing session can end (e.g. user erases, system OOMs, battery falls out)
- [x] #2014 Historical context on WebView behavior: summarize the existing ways we erase (why there?) and our history of hack fixes (e.g. #1875, #1306).
- [ ] #2015 Identify and implement the fix (can we make our two erase entry points to one entry point?)
- [ ] #2016 Adjust (and add to?) our tests to incorporate our changes
- [ ] #2017 Document the erase strategy caveats in the high-level goals document

---

Splitting from #1472 to avoid scope creep:

> Notes:
> - We have three kinds of erases: erases with a WebView instance, erases with static WebView methods, and erasing the files on disk. I'd suggest merging the last two.
> - We call each of these three at different times for what seem like a lot of redundant calls, e.g. when sessions becomes empty (delete files on disk), onPause and finishing (delete files on disk), when the erase button is actually hit (all three)
> - The methods are confusingly named, especially with the extra layers of abstraction like WebViewProvider
> 
> We should try to centralize the erase so it only happens in one place and perhaps when starting a completely fresh browsing session (since that's the workaround for #1306).
>
> Another note (for another bug?): @pocmo mentions we erase these files whenever a tab is removed (via back) and this seems extreme.

**Comment by mcomella** [comment]
Sebastian wrote an analysis of our goals in https://github.com/mozilla-mobile/focus-android/issues/1306#issuecomment-336226016. Here's the short version:

> We say we do not store any history etc. - So I think our requirements are:
> - Make sure that we do not accumulate traces of browsing history on disk. Temporary caches are okay.
> - Do not leak any data to other apps.
>
> I think as long as we stay in those bounds we can be flexible.

I think we should document this guideline on the wiki so we can always look back to it when making decisions (such as the safety of this PR https://github.com/mozilla-mobile/focus-android/pull/1570#pullrequestreview-72872647 ).

**Comment by liuche** [comment]
Decided to discuss this offline with engineers to:
* Explain user benefit
* Discuss breakdown: regression tests, better approaches

**Comment by mcomella** [comment]
Note: there's an untriaged bug open for having an "UNDO" action in the "history erased" snackbar: #467.

**Comment by mcomella** [comment]
^ Please see these reference issues for more we should consider when completing these issues.

**Comment by liuche** [comment]
Engineers still have an action item to meet and discuss a strategy for this.

**Comment by jenn-chaulk** [comment]
Kamino cloned this issue to mozilla-mobile/focus-android

**Comment by mcomella** [comment]
I did a not-too-thorough analysis of our current erase calls in https://github.com/mozilla-mobile/focus-android/issues/1875#issuecomment-349488964.

**One questionable detail**: we only delete *all* the data via the Chromium APIs when back is pressed or the user clicks the trash can. Otherwise, we fall back on deleting WebView's files which may not delete everything.

**Comment by mcomella** [comment]
Note (to self?): we should enumerate all the ways the user can delete data/close the app when coming up with a strategy such as trash can, notification (background, foreground), "3D touch" press, swipe to close, OOM, force quit, etc.
