### ISSUE TITLE
[meta][ux] improve custom tabs experience

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#1624]
The UX ticket for this work:

Breakdown:

- [x] #1625 research and consider prior work
- [x] #1626 design (may be multiple phases)
- [x] #1627 first implementation
- [ ] #1628 iterate designs ⬅️ (We are here) – does it perform as user expected?
- [x] #1629 deliverables (may not be necessary)

**Comment by bbinto** [comment]
@Sdaswani; fyi, discussed with @brampitoyo that he will finish this work up by end of workweek so eng can start working on this for 5.0

**Comment by pocmo** [comment]
@brampitoyo This is in our 4.1 milestone. Is there still UX work to be done here? Or is this something we should move to one of the next milestones?

**Comment by brampitoyo** [comment]
The design work itself has finished. I originally wanted to keep this issue open, to observe tweaks that we’ll need to make after the feature launches. But let’s use a new issue for that, when we need it.
