### ISSUE TITLE
Polish: ensure consistency of colors throughout the app

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1657]
Here are the colors (and possible names):
- [ ] Dialog Black 100% (#272727)
- [ ] Dialog Light Grey 100% (#414146)
- [ ] Pressed state on Dark 100% (#38383D) = Grey 70
- [ ] Hint text white 40% (#80FFFFFF)
- [ ] Blue links 100% (#0A84FF) = Blue 50
- [ ] White links 100% (#FFFFFF)
- [ ] URL string 100%  (#B2B2B2)

Please ensure all the UI elements are using these colors and that they're sharing a single resource (e.g. `R.color.dialog_black`) – you can get an idea where these colors are used from the mocks in #1260.

**Comment by mcomella** [comment]
@layely has been working on this. FYI to layely that I broke this out from #1260.
