### ISSUE TITLE
[meta] UI audit of dialogs/ context menus in app

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1659]
breakout from https://github.com/mozilla-mobile/focus-android/issues/1260:

Here are the views I think this includes
- [ ] #1658: Overflow menu (home and content)
- [x] #1520: Add to Home screen dialog (sometimes with Hint UI for TP disabled status)
- [x] #1466: Context menu on long-press (sometimes with Hint UI for Saving images/downloads)
- [ ] #1657: Ensure color consistency in app

---

Note: @layely has been working on these issues.
