### ISSUE TITLE
[meta] Support for custom autocomplete domains

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1766]
From: #1525 Quick access to favorite sites.

Mocks: https://github.com/mozilla-mobile/focus-android/issues/1609#issuecomment-345856966

- [x] #1767 - Add functionality to save and load custom domains for autocompletion
- [x] #1768 - Add settings for enabling/disabling autocomplete
- [x] #1769 - Add settings UI for adding custom autocomplete URLs
- [x] #1770 - Add settings UI for removing custom autocomplete URLs
- [x] #1771 - Add telemetry probes for autocomplete
- [x] #1781 - Let users reorder entries
- [x] #1813 - Change default value for settings
- [ ] #1754 - "Learn more" SUMO pages
- [ ] #1790 - UI tests

**Comment by pocmo** [comment]
#1830
