### ISSUE TITLE
[meta] Improve custom tabs experience

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1870]
UX issue: #1626

What we want to do so far:

- [x] #1358 - Always show a "Share" menu item
- [x] #1871 - Show a share button in the custom tabs toolbar if the third-party app does not define an action button
- [x] #1529 - Always show a "Open with Firefox Focus" menu item in custom tabs

added by @bbinto on Feb 23
- [x] #1282 
- [x] #770

Feature requests:
- [ ] #2183 - Navigation events

From ahunt's ticket #610 

- [ ] Bottom toolbar support (not use much IRL?)
- [ ] URL copying (the urlbar doesn't allow editing, FF and chrome let you long-press to copy the current URL)
- [ ] Consider showing page title in the urlbar (similar to firefox CT)
- [ ] In/out animations
- [ ] Pre-warming (that might not be possible given we're using webview?)
- [ ] Show page title (EXTRA_TITLE_VISIBILITY_STATE)
- [ ] Action button tint

We might not want and/or be able to support all of these, but at least we can track what features we don't support here.

**Comment by pocmo** [comment]
The things from the UX wishlist and from barbara's wishlist are implemented. I moved the things from ahunt's list into separate issues. We should triage them separately and decide.
