### ISSUE TITLE
[meta] Add manual search engine feature is unintuitive

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1879]
- [x] #1939: Move error messages in "Add search engine" under input fields
- [x] #1935: Add "Learn more" link to "Add search engine" page, under "Example:"
- [x] #1936: Add additional validation (just making a network request? we already %s)

---

The example text shows:
Example: example.com/search/?q=%s
but if you follow this format, it won't work, because it's missing https://.  It'll return about blank page

For example, typing www.bing.com/search?q=%s into the search engine definition will return about:blank page, but if I type www.bing.com/search?q=hello into the URL bar, it works fine, probably because the latter autodirects to https.  Either the example should be updated, or the search should auto-handle http prefix.

**Comment by liuche** [comment]
However, this works fine for Yahoo - it creates the https:// search query.

**Comment by mcomella** [comment]
fwiw, I explicitly typed http://www.bing.com/search?q=test in Safari and it remained an http (insecure) query.

**Comment by npark-mozilla** [comment]
oh, just found out that in focus if the engine is defined as http://www.bing.com/search?q=%s, it autodirects to https://. the problem is when there is no http:// or https:// prefix.

**Comment by liuche** [comment]
In any case, it shouldn't return about:blank. If bing.com doesn't redirect to https but rather http, I'll have to think about whether that's something we should fix (like a built-in https-everwhere? but that is maybe outside the scope of this bug).

**Comment by pocmo** [comment]
> like a built-in https-everwhere

-> #596

**Comment by bbinto** [comment]
Discussed a quick fix in x-functional 
- Validate on user's input, return error message if search query is incorrect and point user to SUMO page
- Add "learn more" under add to search engine screen
- @bbinto to work with @jonisavage and Roland to add examples to SUMO page
- @bbinto to work with marketing to address this feature as a power user feature to set expectations

**Comment by liuche** [comment]
@bbinto what does "incorrect" specifically mean here?
a) Missing %s
b) Doesn't resolve to a webpage (might show about:blank)

**Comment by bbinto** [comment]
ideally both, @liuche -- I think we already validate on the %s no?

**Comment by liuche** [comment]
Okay, that makes sense - and yes, we already validate on %s.

**Comment by liuche** [comment]
@bbinto I'm a little hesitant about adding the requirement for a "webpage loads" check because the user might not have internet (or the request times out) and that adds more explaining that has to go to the user for what is going wrong - I'll talk to @antlam about this.

**Comment by bbinto** [comment]
@liuche, can you clarify what @antlam can help here with? Let's not waste that much time to find the perfect solution, I'm ok with excluding "the user does not have internet connection" use case for 4.0 and figure out a proper solution for the next iteration.

**Comment by liuche** [comment]
I've been talking to @antlam about the case (which does not exist at all) of "check the url to make sure it returns something". Namely, if it fails, we need to communicate to the user what went wrong (so they can fix it) or if it's something like "you don't have network".

**Comment by Sdaswani** [comment]
> Namely, if it fails, we need to communicate to the user what went wrong (so they can fix it) or if it's something like "you don't have network".

I think lumping all the failure into the same error message is fine for 4.0 - we will get more specific in a later release.

**Comment by liuche** [comment]
All sub-issues finished, closing meta.
