### ISSUE TITLE
[meta] Uplift v4.0 release blockers

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1909]
- [x] #1906 and detekt failure fix #1918 
- [x] #1896 
- [x] #1924 (full or partial fix for #1922 )
- [x] #1876 
- [x] #1931 
- [x] #1935 
- [x] #1936 
- [x] #1939 
- [x] #1957 
- [x] All the l10n imports

Assigning to releng.

**Comment by liuche** [comment]
All sub-issues uplifted.
