### ISSUE TITLE
[meta] Klar with GeckoView

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2059]
- [x] Update GeckoView shipping with Focus/Klar https://github.com/mozilla-mobile/focus-android/issues/2056
- [x] https://github.com/mozilla-mobile/focus-android/issues/2090
- [x] https://github.com/mozilla-mobile/focus-android/issues/2088
- [x] https://github.com/mozilla-mobile/focus-android/pull/2087
- [x] https://github.com/mozilla-mobile/focus-android/issues/2084

**Comment by ekager** [comment]
This meta is not helpful to me, so I am closing. Reopen if you disagree.
