### ISSUE TITLE
[meta] Refresh visual design to optimise for Android P

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2676]
### Why/User Benefit/User Problem

* Our visual design is not yet optimised for the upcoming version of Android
* When Android P is released, our users may not feel as confident using our browser as they are using another product

#### URL bar

* [x] #2677 URL bar – active (initial state only)
* [x] #2678 URL bar – active (typing)
* [x] #2679 URL bar – loading
* [x] #2680 URL bar – site loaded, Tracking Protection ON
* [x] #2681 URL bar – site loaded, Tracking Protection OFF

#### Floating Action Button (FAB)

* [x] #2682 Erase
* [x] #2683 Multitasking (number of tabs)

#### Menu & dialog

* [x] #2684 Multitasking (list of tabs)
* [x] #2685 Main menu
* [x] #2686 Context menu
* [x] #3035 Add to Home screen

#### Page

* [x] #2687 Settings

**Comment by brampitoyo** [comment]
@Sdaswani @ekager @boek The theme design meeting happened last Friday US time. @aminalhazwani kindly presented the designs I’ve posted here.

As a result of that meeting, we’ve received the go-ahead to move forward – particularly with the dark blue (ink) colour scheme. We can now implement it using the specs provided.

Thanks for waiting!

**Comment by brampitoyo** [comment]
@bbinto Since these design changes are partly about design alignment with Photon, and partly about Android P, I think that we should start talking to the Play Store team right after we ship it on the Dev channel. If they’d like anything amended, we may expect some more design work to happen.

And we’ll need to coordinate the release date so that it coincides with the release of Android P?

**Comment by bbinto** [comment]
Adding marketing here, @cherrypark

**Comment by brampitoyo** [comment]
All design is now finished. The only thing that remains is to implement them.

We will wait for v7.0 – closer to the release of Android P – to ship these visual changes.

**Comment by bbinto** [comment]
re-open to use this as the meta for eng

**Comment by colintheshots** [comment]
These should all be closed and working in Nightly-- the 7.0 branch.
