### ISSUE TITLE
[Meta] Make Custom Tabs Great

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/focus-android#2997]
This is a meta bug to contain all the ways we should return Custom Tabs to an epic era of greatness. Outside browsers brought Chrome and violins (Opera/Vivaldi). They're bringing tabs. They display lists. And some, I assume, are good browsers.

- [ ] Custom Tab UX When Trashing the Session Is Confusing #2996
- [ ] Custom Tabs: Support pre-warming #2300
- [ ] Custom Tabs: Support custom animations #2299
- [ ] Custom Tabs: Consider showing page title in URL bar. #2298
- [ ] Custom Tabs: Support bottom toolbar #2296
- [ ] Focus' custom tab opens in a separate task #2203
- [ ] Add animation when switching from custom tab to full browser #2188

**Comment by bbinto** [comment]
Great summary, @colintheshots - I'd love to get estimates for all of them, if possible (for the ones that might have had @brampitoyo look at it already).

Could we split this up into most useful ones to least useful / used ones?

I could see #2300 the most useful to the user as it will make our browser feel faster.
