### ISSUE TITLE
[Meta] Turn on GV for 50% of 7.0 Beta Users

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3327]
- [x] @mmccorks to create tracking dashboard https://github.com/mozilla-mobile/focus-android/issues/3325
- [x] @colintheshots to verify fretboard regexp can target *only* 7.0.1 builds
- [x] @boek to create 7.0.1 release and push to beta
- [x] @boek to confirm we send active experiments in the 'experiments' field of the core ping
- [x] @mmccorks to confirm we **don't** need to send experiments in the event ping: https://github.com/mozilla-mobile/android-components/issues/713

**Comment by colintheshots** [comment]
I confirmed the active experiments were sent in the core ping. https://sql.telemetry.mozilla.org/queries/58774/source

**Comment by colintheshots** [comment]
@mmccorks told me she could work with the active experiments data we're sending in the core ping for now. Is that right?

**Comment by mmccorks** [comment]
It would be nice to have the experiment name in the future but to avoid blocking this release I can work with the UUID for this experiment.

**Comment by mmccorks** [comment]
Confirming we don't need the experiments in the event ping for this dashboard - there will be no event level data to compare between geckoview and webview but will still have all metrics possible from the core ping (DAU, retention etc)

**Comment by Sdaswani** [comment]
@colintheshots to be clear https://github.com/mozilla-mobile/focus-android/pull/3332 does not block this ticket?

**Comment by colintheshots** [comment]
@mmccorks Said she could use experiment IDs for the time being until the next version is out. They look like GUIDs and aren't human-readable, but I gave her a link to the definitions of them.

**Comment by Sdaswani** [comment]
This is closed - great work everyone!
