### ISSUE TITLE
7.0.13 release checklist

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3792]
- [x] Tag the RC version using Github releases
- [x]  [Ping release management](https://bugzilla.mozilla.org/show_bug.cgi?id=1483629) to promote the build to beta
- [x] Upload the APKs to the release page
- [x] Upload the APKs to archive.mozilla.org into a folder with the name of the version (e.g. /android/focus/2.2-RC1) (S3 bucket)

**Comment by colintheshots** [comment]
Release is out in beta and uploaded. All good!
