### ISSUE TITLE
[Meta] 8.0 beta blockers

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3882]
# Required
- [x] #3856 - Geckoview scrolling ANR
- [x] #3826 - Tracking protection does not work
- [ ] #3501 - Password Manager autofills password into username field
- [x] #3849 - Update to AC 0.31.0
- [x] #3871 - Add Telemetry for Exceptions List

# Nice to have
- [x] #3865 - Sumo links

**Comment by ekager** [comment]
GeckoView ANR fixes coming in https://bugzilla.mozilla.org/show_bug.cgi?id=1479039

**Comment by ekager** [comment]
Should we also add #3826 ? Bugzilla is here and fixes should also be coming to 64 this week: https://bugzilla.mozilla.org/show_bug.cgi?id=1503560

**Comment by ekager** [comment]
Updating to AC 31 (coming out tomorrow Tues Nov 13) also includes new coroutine fixes that @colintheshots is working on

**Comment by Sdaswani** [comment]
@colintheshots do you have a bug you are working under for the 31 migration work?

**Comment by cpeterso** [comment]
> Should we also add #3826 ?

I don't think #3826 needs to be a beta blocker (but I think it should be a blocker for testing GV 64 for Focus 8.0 prod users). Comparing GV without Tracking Protection to WebView _with_ Tracking Protection is not a fair performance comparison, but getting GV crash reports from Focus 8.0 Beta users is a higher priority.

**Comment by Sdaswani** [comment]
That makes sense @cpeterso - we need to get the crash reporter to beta ASAP.
