### ISSUE TITLE
[meta] Home Screen Surveys

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3925]
### Why/User Benefit/User Problem
We want to serve our users with the features and capabilities they want, and understand what they would like improved about our Mozilla products.

### What / Requirements
- [ ] Fretboard Should Serve Survey JSONs via an Experiment
- [ ] Focus Should Consume Survey JSONs
- [ ] Focus Should Present Survey Request in Home Screen Tip
- [ ] Focus Should Survey User
- [ ] Focus Should Report Survey Results Via Event Ping

As much as possible this should be done in reuseable Android Components.

### Acceptance Criteria (how do I know when I’m done?)
A user in the wild can be put in an experiment bucket with an associated survey json, opt in to the survey via a home screen tip, and user's answers can be reviewed by us via redash dashboard.

**Comment by Sdaswani** [comment]
@colintheshots @boek @ekager would love your thoughts here.

**Comment by Sdaswani** [comment]
and @sblatz !

**Comment by vesta0** [comment]
A couple of clarifying questions for @Sdaswani 

1- I assume (if we are using fretboard) that we only want to expose the survey tip to a percentage of users. What would be a sample use case? Do we want to compare survey results from users who get a specific feature to users who didn't get that feature? (e.g. compare user satisfaction of users who have access to ad blocking to users that don't)

2- Are you envisioning a short 1-2 liner survey ('rate this feature' or 'are you happy with this feature' yes/no) or longer/more qualitative answers? And would the actual survey happen within the app?

**Comment by Sdaswani** [comment]
@vesta0 

We can expose the survey tip to as many users as we want. Fretboard serves two purposes in this system:

1. Server Side CMS for Survey Content: All surveys are configured in Fretboard, and are delivered to all clients via Fretboard.
2. Server Side A/B Platform for Specific Surveys: Specific surveys are enabled via Fretboard.

We could very well do you what you suggest, but I really just wanted to survey as many users as possible learn from them.

The survey could be short or long - in 1 above, Fretboard can deliver surveys that are rendered in a web page in the app. Obviously we want to keep the surveys pretty short so folks convert.
