### ISSUE TITLE
Disable content blocking for current browsing session

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#443]
**Theme:** _General Improvement_

**User Story**

> As a user who has Focus set as a default, I want to be able to turn on/off blocking on a per page basis, in case pages are broken. I don't want to open it with any other browser to interrupt my current task

**Feature**

* Per site blocking (Turn on/off per page basis)
* Turn off individual blocklists per webpage, session?

**Background**

Sometimes a website is broken because of blocked trackers. Because all browsing data is deleted anyways a user may want to disable the blocking temporary (without going to settings and back and reloading and then enabling again, ...) to just get to the content.

**Tasks**
- [x] Define scope: Do we want to turn of blocking per site or temporarily for the session? Do we need fine-grained control or just a global on/off?
- [x] UX mocks / flow
- [x] ~(_Maybe_) keep track of per-site settings~
- [x] Implement UI for turning blocking on/off
- [x] Copy
- [x] Add telemetry probes

**Comment by bbinto** [comment]
Does it make sense to split it further into
- by session (while the app is running)
- by website, e.g. I might want to turn off blocking on website x, but continue with blocking for all other websites I visit during the current session (I think that's how Brave does it)

**Comment by pocmo** [comment]
@antlam What's your take on this from UX point of view?

I wonder whether we have any user research (maybe about tracking protection?) that helps us understand if regular users understand those kind of controls and how fine-grained they can be.

**Comment by antlam** [comment]
@pocmo Yeah good point. There's probably some useful information we've learned from TP.

@bbinto do you mind reaching out to UR and seeing what recommendations they might have here? I'll try to do the same too when I have some time.

**Comment by bbinto** [comment]
I couldn't find anything specifically relevant to our question in the existing research documents. Also, talking and thinking about this some more, I'd propose to keep it simple and just do it on "per session"

**Comment by pocmo** [comment]
@antlam I need some guidance here. I implemented the functionality and so far I've been using a switch in the menu. But I'm not sure if this is the way we should present this option to the user?

![blocking-switch](https://cloud.githubusercontent.com/assets/89638/25484933/44f9b4f6-2b5c-11e7-9d5b-b295952f3971.png)

(The text is just a placeholder)

**Comment by antlam** [comment]
> I'd propose to keep it simple and just do it on "per session"

Per session is fine. I think it should be clear enough to users once they Erase.

>  so far I've been using a switch in the menu.

That's actually what I've been thinking about too. But as I understand it, flipping this switch will _also_ reload the page right, @pocmo ? So it should close the menu, and reload the website?

I'll need to think about this menu's ordering a bit if we introduce this feature here. But I think it makes sense so far.

**Comment by pocmo** [comment]
> That's actually what I've been thinking about too. But as I understand it, flipping this switch will also reload the page right, @pocmo ? So it should close the menu, and reload the website?

Yeah, that's exactly how I implemented it. The menu closes and the website reloads. If we come up with an ordering and (temporary) string then I'll land this and we can already start to test it.

**Comment by antlam** [comment]
Michelle's suggestion is to go with "Disable content blocking" here. Can we try that @pocmo ?

**Comment by pocmo** [comment]
"Disable content blocking ON/OFF" sounds like a logic riddle - are you sure about that? Our settings speak about blocking trackers and do not mention "content blocking".
