### ISSUE TITLE
Integrate feature-media component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4565]
For media controls etc.
Tickets:

- [x] https://github.com/mozilla-mobile/focus-android/issues/6330
- [x] https://github.com/mozilla-mobile/focus-android/issues/6384
- [x] https://github.com/mozilla-mobile/focus-android/issues/820

**Comment by ionutbedregeanu** [comment]
Since its not obvious at a first look  what should we do and what we can integrate from feature-media in Focus I will create a a new ticket for investigation.
After that other tickets will be created for every functionality which should be implemented

**Comment by ionutbedregeanu** [comment]
https://github.com/mozilla-mobile/focus-android/pull/6450
