### ISSUE TITLE
[Meta] Bring Focus Search Telemetry up to date and at par with Fenix

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4778]
### Dependencies:

- [x] upstream the current telemetry to AC to then be shared by all products - https://github.com/mozilla-mobile/android-components/issues/7249
- [x] resolve current security issues - https://bugzilla.mozilla.org/show_bug.cgi?id=1698456
- [x] use the new AC telemetry in Fenix - https://github.com/mozilla-mobile/fenix/issues/20229
- [x] use the new AC telemetry in Focus - https://github.com/mozilla-mobile/focus-android/issues/4967
- [x] Data Collection Renewal until 2022-07-01.

**Comment by pocmo** [comment]
This is the original A-C issue about upstreaming the functionality from Fenix to A-C to be used in our other apps (like Focus):
https://github.com/mozilla-mobile/android-components/issues/7249

**Comment by Mugurell** [comment]
Thank you Sebastian!
Will look into upstreaming the current functionality from Fenix to AC and then use it in both projects.

**Comment by Mugurell** [comment]
Implementation was verified on both Fenix - https://github.com/mozilla-mobile/fenix/issues/20229#issuecomment-884943406 and Focus https://github.com/mozilla-mobile/focus-android/issues/4967#issuecomment-893411693 so we can close this as done.
