### ISSUE TITLE
Show notification while browsing session is active

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#492]
**Themes:** _General Improvement & Android Advantage_

**User Story**

> As a user I want to know if Focus is still running and stores information I might want to hide

**Tasks**
- [x] Show notification while browsing session is active
- [x] Clicking the notification should erase the browsing session.
- [ ] ~Show feedback in notification for short amount of time (like gmail)~
- [x] Update copy
- [x] Add telemetry probes

**Comment by pocmo** [comment]
![notification_focus](https://cloud.githubusercontent.com/assets/89638/25275988/5072f5f4-2698-11e7-8943-9bccfc46b1da.png)

That's the current state. For now I just used the accessibility string for the "erase" button - @antlam What should we use here? (And should we update the accessibility string too?)

For reference, this is the Chrome notification for incognito mode:

![notification_chrome](https://cloud.githubusercontent.com/assets/89638/25276018/787e11c8-2698-11e7-8adb-0bc1a433995f.png)

**Comment by antlam** [comment]
Yeah I think we should keep the accessibility string for the "erase" button in mind when we come up with the copy for this.

@mheubusch do you have time to look at both for us? 😸

**Comment by pocmo** [comment]
Another way to erase the session is the app shortcut (#499) - I guess we want to use the same string/wording there too (shortcuts can have a "short" and "long" version of the string).

**Comment by antlam** [comment]
@pocmo got some help from Michelle!

> I think where we have room let's say "Erase browsing history" and where we don't just say "Erase"
