### ISSUE TITLE
Onboarding tour

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#497]
**Theme:** _General Improvement_

**User Story**
> As a user I want to know what features Focus provides, and why/how it's different from other Android browsers

**Feature**
> Onboarding tour, e.g. focus on default browser & how to install search widget 

**Details**
> Highlighting the use of Focus as the default browser & differentiator to Chrome. Is there a way to help them install the widget?

**Tasks**
- [x] Define scope: What kind of screens do we want to show? Do we need any special functionality?
- [x] UX mocks / flow
- [x] Add telemetry probes
- ~[ ] Show edge of next card depending on screen size~ Skipped - Not v1.
- [X] Adjust card size for smaller screens / landscape

**Comment by bbinto** [comment]
Goal:
reassure the user that they've made the right decision to download Focus, provide value prop & hint at advanced/convenient features

a) Promote 1-2 not so obvious features
--> If site breaks, conveniently turn off/on tracking 
--> erase at your fingertips: inform about clearing active session in system notifications

b) Promote Focus as default browser or choice of browser for different tasks
-- somehow convey to the user that once they've set Focus as their default, opening web links inside other apps (using custom tabs) will provide all the features that come with Focus, i.e. ad blocking etc. horrible wording, but we'd need Michelle to help us here.

**Comment by bbinto** [comment]
(The shortcuts API can be shown/introduced in the app store screenshots)

**Comment by antlam** [comment]
![screen shot 2017-04-28 at 12 42 23 pm](https://cloud.githubusercontent.com/assets/1994820/25544647/3b968e02-2c10-11e7-9464-0ba4667da063.png)

@pocmo this is the mock for iOS, do we still have that text below the CTA button?

**Comment by pocmo** [comment]
Mock

![image](https://cloud.githubusercontent.com/assets/89638/25705078/43d3d324-30dc-11e7-8935-763d3096f253.png)

**Comment by antlam** [comment]
![screen shot 2017-05-19 at 12 39 09 pm](https://cloud.githubusercontent.com/assets/1994820/26377580/ba253c1e-3fc5-11e7-867d-f27808eaebee.png)

[Onboarding_img.zip](https://github.com/mozilla-mobile/focus-android/files/1023830/Onboarding_img.zip)

**Comment by bbinto** [comment]
@antlam, what happened to the system notification hint? ("erase at your fingertips: inform about clearing active session in system notifications") Did we decide to not include it in the onboarding?

**Comment by antlam** [comment]
Maybe @mheubusch knows more but, I don't remember including that in the onboarding tour before.

**Comment by mheubusch** [comment]
Hi Barbara - I never took the parens off the copy so  part of the copy was cut off when it was comped: 
Browse like no one’s watching
Automatically block online tracking while you browse. Then remove visited pages, searches, cookies and passwords with a touch to the trash icon in Focus or in Android system notifications.

**Comment by antlam** [comment]
@mheubusch Ah my bad! I must've been using old copy strings then! let me put this back in.

**Comment by antlam** [comment]
![screen shot 2017-05-24 at 10 32 54 am](https://cloud.githubusercontent.com/assets/1994820/26416952/7d5a7ebe-406c-11e7-90d0-ac94f6fa6afa.png)

cc @pocmo

**Comment by pocmo** [comment]
Pixel XL

![pixelxl](https://cloud.githubusercontent.com/assets/89638/26638679/001b8a6c-4623-11e7-9fd9-1750933b2145.png)

**Comment by pocmo** [comment]
Sony Z3 Compact

![z3c](https://cloud.githubusercontent.com/assets/89638/26638714/2068eb2a-4623-11e7-97ee-ef98b041ac77.png)

**Comment by pocmo** [comment]
Nexus 9

![nexus9](https://cloud.githubusercontent.com/assets/89638/26638725/271d5f78-4623-11e7-9168-45fb56ad118c.png)

**Comment by pocmo** [comment]
@antlam See screenshots above: Pixel XL, Sony Z3C, Nexus 9 - That's the latest state (not in Beta yet).

**Comment by antlam** [comment]
@pocmo awesome! let's start centering these
