### ISSUE TITLE
Make number of blocked trackers visible

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#498]
**Theme:** _General Improvement_

**User Story**

> As a user I want to see how many trackers have been blocked on a page, so I feel safer knowing what the product does

**Feature**

* Shows the number of ads/trackers blocked
* By session, page, total

**Tasks**
- [x] Define scope (What do we count exactly? Do we count per session / webpage?)
- [x] UX mocks / flow
- [x] Count trackers and persist count
- [x] Add UI for displaying counts to user

**Comment by ahunt** [comment]
As an extension on the scope part, what do we count as a tracker?
- single URL
- single full domain (foobar.imatracker.com)
- single blocked/base domain (anything from imatracker.com)
- single owner (anything from TrackerCorp including trackercorp.com, trackercorp.ca, etc)

The lower you go in the above list, the harder the implementation gets. The last option would require significant rework of our blocklist code (and I would argue is infeasible to do well since e.g. google domains are split across ads/tracking/social lists, so we'd have to reunify that - which would be messy to implement).

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Shows the number of ads/trackers blocked](https://trello.com/c/VaSzbZbJ/15-shows-the-number-of-ads-trackers-blocked)
