### ISSUE TITLE
Support app shortcuts

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#499]
**Theme**: Default Browser & Android Advantage

**User Story**

> As a user I want to know if Focus is still running and stores information I might want to hide

**Feature**

> Add a "erase" shortcut to Focus launcher.

**Docs**

https://developer.android.com/guide/topics/ui/shortcuts.html

**Tasks**
- [x] Add "erase" shortcut and trigger same path like erase notification
- [x] Update copy: (Short) "Erase", (Long) "Erase browsing history"
- [x] Add telemetry probe

**Comment by pocmo** [comment]
![shortcut](https://cloud.githubusercontent.com/assets/89638/25432987/0c26abe6-2a87-11e7-9f46-a58b4cc4b226.png)

@antlam That's how the shortcut looks like currently. Like with the notification we do not show any feedback currently. Is this something we should do? Or should we even switch to the app?

**Comment by antlam** [comment]
@pocmo I think this is fine for now. Switching back to the app seems weird, unless there's a web page open maybe. Then the user would just see the toast on the home screen.

Is it hard to make the shortcut button the same color/UI as it is in App?

**Comment by pocmo** [comment]
> Is it hard to make the shortcut button the same color/UI as it is in App?

What color did you have in mind? I think I took the FAB color for this. I used the app shortcut icon generator from the asset studio: https://romannurik.github.io/AndroidAssetStudio/

**Comment by antlam** [comment]
Basically, the same purple button color as our in-app FAB. and white for the trash can icon.

**Comment by bbinto** [comment]
Do you think we should add more shortcuts?

**Comment by pocmo** [comment]
![erase_icons](https://cloud.githubusercontent.com/assets/89638/25530464/9dcee0cc-2c26-11e7-972c-1d17adffd11c.png)

**Comment by antlam** [comment]
ship it!
