### ISSUE TITLE
Support "Custom Tabs" UI customizations

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#500]
**Theme:** _Default Browser & Android Advantage_

**User Story**

> While using shopping apps or reading shopping email promotions, I want to have peace of mind to not be tracked for any link I click.

**Details**

> Discuss UI for custom tabs, can we leverage current 3 dot menu from Focus chrome?

**Technical details**

* https://developer.chrome.com/multidevice/android/customtabs

**Tasks**

- [x] Define scope: What UI customization features do we want to support (in v1)? How do we implement them without completely giving up the Focus branding?
- [x] Customization: Support toolbar color
- [x] Customization: Support action button
- [x] Customization: Support custom menu items
- [x] Hide erase button (but erase when going back to previous app via up/back button)
- [x] Show "X" up button
- [x] Add telemetry probes
- [x] "Maybe we could extend the FloatingActionButton class to permanently hide the button in some states."
- [x] Tests

**Not in scope**
- Pre-warming
- "May open URL"
- Up button customization
- Custom in/out animations
- Bottom toolbar
- "Up button" customization

**Comment by ahunt** [comment]
Another UX question: *if* we add a bottom toolbar, do we want to make it disappear, when scrolling, similar to the FAB? (Chrome usually does that, although it was disabled for some time in Chrome Dev.) I'm guessing that's what app devs will expect, so we probably should do this.

**Comment by pocmo** [comment]
I'm pretty certain that we are not going to support the bottom toolbar. It's not used much and we already decided to not implement it in the first iteration in Fennec.

**Comment by ahunt** [comment]
Further TODOs:

- [ ] Import SafeIntent (or find alternative), and use that elsewhere in Focus too
- [ ] Check close icon size (as supplied by external app)
- [ ] And close icon padding
- [ ] Consider long-press to copy URL (similar to chrome - what does Firefox do?)
- [ ] Tests for intent handling

**Comment by ahunt** [comment]
I'm still wondering what telemetry probes we want, here's what I've though of sofar:

- [ ] Custom tab opened (vs normal URL opened)
- [ ] Custom tab specific features used, i.e. included in the intent (action button / menu item / bottom toolbar etc)
- [ ] Custom tab feature selected by user (exited using back button vs up button vs using CT menu item/actionbutton/etc)

**Comment by ahunt** [comment]
As described in https://bugzilla.mozilla.org/show_bug.cgi?id=1365167 it's possible for the Bundle extras that are used for UI customisations to contain garbage. My latest patches include a SafeBundle (similar to SafeIntent) to fix that, so we shouldn't be affected by any issues there.

**Comment by ahunt** [comment]
And a bug where we keep custom tab customisations when we shouldn't, STR:
1. launch focus via custom tabs
2. Exit via system back button (not reproducible when using actionbar back button
3. Use app switcher to return to focus
4. open website

Actual: custom tabs appearance is still there
Expected: normal Focus appearance

Also note: the clear notification stays visible after (2), whereas it disappears if you exit using the ActionBar back button.

**Comment by pocmo** [comment]
This sounds like the same bug I fixed for normal view intents. With the steps you described above Android will re-deliver the old intent when the activity was started. I added code to ignore the VIEW intent in this case - I guess you will need to extend this to ignore the CAT data too.

**Comment by ahunt** [comment]
So I've found the issue: we keep the BrowsingSession alive when exiting via the back button, which also means that the CustomTabConfig remains. Our FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY only executes if !BrowsingSession.isActive(). I'm not too sure if calling BrowsingSession.stop() in BrowserFragment.onBackPressed() is correct, I'll need to think a bit more about that.

**Comment by ahunt** [comment]
The toolbar button paddings and placements still need to be decided (the rest of the actual custom tab support code has landed).

@antlam - feedback welcome (the X button is shown for all custom tabs, and can be replaced by an icon that the app provides. The black phone icon is an icon that the app opening custom tabs supplied.):
![phone](https://cloud.githubusercontent.com/assets/1546915/26325635/8f003dc4-3eec-11e7-8acc-43e19f89833f.png)
![tablet](https://cloud.githubusercontent.com/assets/1546915/26325636/91df627c-3eec-11e7-9e83-a216e0a55d80.png)

**Comment by ahunt** [comment]
notes from meeting:
- action button: Padding/sizing the same as refresh button (24dp square sizing)
