### ISSUE TITLE
Allow saving of images in a website

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#502]
**Theme:** _Default Browser_

**User Story**

> I discovered content of a page that I want to revisit later (save to my device)

**Feature**

> Save images inside web pages
> (Warning that it won't go away after "Erase" was clicked)

**Tasks**

- [x] Add context menu with item for saving image
- [x] UX mocks / flow
- [x] Trigger download of image (See #14 too)
- [x] Add telemetry probes

**Comment by ahunt** [comment]
I'm wondering how much we want to mirror fennec's menu. I.e. in terms of share/view image/copy image location (and of course save). We currently show the share menu when long-pressing an image, so I guess we'll want that in the menu?

(Reminder to self: test images that are inside a link. HitTestResult only allows one type, whereas e.g. gecko can return both an image and a link.)

**Comment by pocmo** [comment]
> (Reminder to self: test images that are inside a link. HitTestResult only allows one type, whereas e.g. gecko can return both an image and a link.)

Oh, yeah, that's something I wanted to file! When long pressing an image with a link I get a share menu for the image URL. This seems wrong.

> We currently show the share menu when long-pressing an image, so I guess we'll want that in the menu?

This one is tricky. Right now we share the URL of the image. But at times I want to share the actual image. Maybe we need two menu items. Anyways, let's file separate issues and talk about them with antlam or in triage.

**Comment by ahunt** [comment]
I've filed #531 to fix the image bug (I already had that code as part of this bug), deassigning this one for now since it's not V1.

**Comment by pocmo** [comment]
@antlam Copy for dialog(?) to inform the user that the image will be saved permanently

**Comment by pocmo** [comment]
I added a patch for downloading images (via context menu). So far without any dialog (except for the permission dialog if needed).

**Comment by brampitoyo** [comment]
@ahunt commented:

> I'm wondering how much we want to mirror fennec's menu. I.e. in terms of share/view image/copy image location (and of course save). We currently show the share menu when long-pressing an image, so I guess we'll want that in the menu?

I think @pocmo is correct that we’d want some sort of a dialogue to pop out. This is practically similar to how the same dialogue would show up when you tap-hold on a link in Chrome or Firefox.

But we’d also like to warn our users that anything which gets out of Focus (through saving, sharing, etc.) won’t get erased when they clear history.

Maybe like these?

![image-copy-share-dialog-i01](https://cloud.githubusercontent.com/assets/51007/26138754/8065c35e-3b1f-11e7-8d26-3730235219f0.png)

The question is, can we modify this dialogue to have a special element for our messaging?

**Comment by brampitoyo** [comment]
Feedback from @antlam: treating the warning as footer note (left) is the right placement.

Now we need to figure out whether it’s possible to put a custom element in a dialogue, and if so, what the copy should be (I’ve written something up above. Is it good enough?)

**Comment by antlam** [comment]
maybe @mheubusch can help us look it over? :)

**Comment by brampitoyo** [comment]
Revising the copy slightly:

> Saved and shared images **will not be deleted** when you clear Firefox Focus history.

![image dialog - mdpi](https://cloud.githubusercontent.com/assets/51007/26387192/3c28af94-4097-11e7-83ac-2a6779eff28d.png)

**Comment by mheubusch** [comment]
Thanks Bram. I missed that copy altogether. Where you say "clear" can you use "erase".

**Comment by brampitoyo** [comment]
Thanks for the suggestion, @mheubusch. I’ve changed the strings to reflect it, and darkened the text so it looks less like a tappable menu item (optional).

![image dialog - mdpi](https://cloud.githubusercontent.com/assets/51007/26428571/319f0f68-412e-11e7-9179-869f1a64b5c9.png)

**Comment by pocmo** [comment]
![focus-context-menu](https://cloud.githubusercontent.com/assets/89638/26496942/d682f19c-4229-11e7-8a86-eeb10651fd51.png)

@brampitoyo This is how the context menu now looks like in my builds. Are there any colors / paddings / margins / sizes / .. you want to change?

**Comment by brampitoyo** [comment]
As long as this menu looks like every other Android menu – which certainly seems to be the case! (I use OnePlus One, which has a different aspect ratio and UI scaling – then we’re good to go. Thanks, @pocmo!
