### ISSUE TITLE
Firefox Focus 8.18.0-rc.1 issues summary

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/focus-android#5024]
I want to collect **all** bugs appeared in Firefox Focus 8.18.0-rc.1 together for convenience.

Reporters: @sv-ohorvath, @lobontiumira
- [x] #4990 - verified as fixed
- [x] #5006 - duplicate of #4990

Reporter: @lobontiumira
- [x] #5011 - verified as fixed
- [x] #5012 - verified as fixed
- [x] #5013 - verified as fixed
- [x] #5014
- [x] #5017 - verified as fixed

Reporter: @sflorean
- [x] #5020 - verified as fixed

Reporter: @Nickoriginal
- [x] #5022 - verified as fixed
- [x] #5040

Reporter: @cadeyrn
- [x] #5023 - verified as fixed
