### ISSUE TITLE
Protected download manager/storage

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#503]
**User Story**

> I want to protect my downloaded content

**Feature**

> Locking browsing session/downloads with fingerprint/PIN

** Tasks **

- [ ] Define scope (This is not really well thought out yet)
- [ ] Define UX mocks / flow
- [ ] Implement downloads screen?
- [ ] Route downloads into app storage (see #14)
- [ ] Allow opening downloads in third-party apps (permission delegation?)
- [ ] Allow removing downloads
- [ ] Add fingerprint protection mechanism?
- [ ] Add PIN protection mechanism? (Not everyone has a fingerprint reader)
- [ ] How to handle forgotten PINs?
- [ ] Add telemetry probes
