### ISSUE TITLE
Search widget with UI focused on search

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#505]
**Theme**: _Default Browser & Android Advantage_

**User Story**

> I want to quickly start a private Focus search from my home screen.

**Feature**

> Search widget with UI focused on search (see Fennec)

**Details**

> Find a quick entry point into Focus for user

**Tasks**
- [ ] Define scope: What do we actually want to implement here?
- [ ] UX mocks / flow
- [ ] Implement widget
- [ ] (_Scope?_) Implement separate search UI?
- [ ] Implement hand-off from search to browser?
- [ ] Add telemetry probes

**Comment by mystor** [comment]
I filed a bug with my ideas for this on Bugzilla, which I now realize is the wrong place. This is my uninformed idea for what a minimal version of this feature would look like:
1. A widget in the launcher the same size and shape as the google search widget. This widget displays the name of the current default search engine, and uses firefox focus colors. 
2. Tapping on this box immediately does the following:
   * If there is a current session, destroy the current Focus browsing session.
   * Open the browser with the search/address combo box already focused, and the keyboard open.

This seems to me like a simple version which hopefully shouldn't add too much work to the implementation, but provides a useful user experience for making private firefox-focused based search your default search on mobile. I would certainly love something like that.

**Comment by ekager** [comment]
I looked into this before and you cannot put an EditText element in a widget due to Android constraints, but you could do a TextView that *looks* like an EditText and when the user clicks it, launches a transparent activity over the TextView that *feels* like an EditText on the home screen.

**Comment by ekager** [comment]
Since the new UI pulls up the keyboard on the home screen + readies for a search, I think the widget would need to add more value than simply opening Focus.

**Comment by ionutbedregeanu** [comment]
I will close this ticket in favour of https://github.com/mozilla-mobile/focus-android/issues/7249
