### ISSUE TITLE
Add "search" action into text selection menu of third-party apps

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#506]
**Theme**: _Default Browser & Android Advantage_

**User Story**

> I want to quickly start a private Focus search from my homescreen

**Feature**

> Include action in text selection menu.

**Example**

![1 d4zzzplbtk5cen9qn0-cba](https://cloud.githubusercontent.com/assets/89638/25283853/78360ff0-26b5-11e7-9396-141559bffe64.gif)

**Technical details**
https://medium.com/google-developers/custom-text-selection-actions-with-action-process-text-191f792d2999

**Tasks**
- [x] Implement text selection action receiver (ACTION_PROCESS_TEXT)
- [x] Trigger search from action
- [x] Update copy: "Search" / "Private Search" / "Focus Search" / ... ?
- [x] Add telemetry probe

**Comment by antlam** [comment]
If it's just adding a "SEARCH" item to the context menu/action bar here that triggers Firefox Focus, then we can just jump right into loading a URL in Firefox Focus after they press "SEARCH"

**Comment by pocmo** [comment]
In Firefox we add the product name: "Firefox search", "Nightly search", ... Should we do this here too? Focus search? Or maybe even Private search?

**Comment by antlam** [comment]
Maybe! but I worry that would seem out of guidelines for these context menu/action bars... 

From my understanding, this SEARCH action is usually done by the default browser. So if Firefox Focus is my default, it seems unnecessary to call that out again in the menu. 

Thoughts?

**Comment by pocmo** [comment]
The action will show up always - independently from whether we are the default browser or not. For example in my case I see search entries for all my Firefoxes and Focus.

**Comment by pocmo** [comment]
> Thoughts?

Users might want to be sure that the action is launching their privacy browser that doesn't keep any history etc. - Launching the search in a different browser might mean that this search will be connected with your profile.

**Comment by antlam** [comment]
> The action will show up always

Ah, my mistaken. Then this makes more sense if we label it explicitly.

**Comment by brampitoyo** [comment]
Some copy ideas other than the ones mentioned above:

* Search with Firefox Focus (too long?)
* Search with Focus

Otherwise, I like “Private Search”. Even though it’s less unique because it doesn’t contain our name, it communicates exactly what user expects: “When I tap on this, my search will not be recorded into history”.

**Comment by antlam** [comment]
@pocmo and I were also talking about "Focus Search" because of the system conventions (Google Search, Yahoo Search, etc)... 

Thoughts @mheubusch ?

**Comment by pocmo** [comment]
>     Search with Firefox Focus (too long?)
>     Search with Focus

They might be both too long. All other system text actions are single words or pretty short: Copy, Cut, Select All, Translate

> @pocmo and I were also talking about "Focus Search" because of the system conventions (Google Search, Yahoo Search, etc)...

So far I have only seen Firefox adding the product name to the action: Firefox Search.

> Otherwise, I like “Private Search”. Even though it’s less unique because it doesn’t contain our name, it communicates exactly what user expects

It turns out that "Private Search" is also much easier to implement than "Focus Search" which consists of dynamic product name (Focus, Klar) and a translated String (Search). This is not supported by Android and I will need to add some build system magic to make this possible.

**Comment by antlam** [comment]
"Search Privately" might make more sense here then?

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Include in text selection menu](https://trello.com/c/0jyksGm1/33-include-in-text-selection-menu)
