### ISSUE TITLE
Show overlay when user copies text

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#507]
_Added by @bbinto_

**Why/User Benefit**
- Quickly/conveniently start a private Focus search from any app without having to open Focus individually

**What**
- Show bubble after user copied text in another app

**Acceptance Criteria (how do I know when I’m done?)**
Following flow needs to work for user:
- If it’s a URL, open Firefox Focus and perform “Paste & Go”.
- If it’s a string of text, perform “Paste & Search” in an overlay. When you tap on any search result, open in Firefox Focus.

----
**Theme**: _Default Browser & Android Advantage_

**User Story**

> I want to quickly start a private Focus search from my home screen

**Feature**

> Google translate bubble like overlay when user copies text

**Alternative feature**
* #506 - Add "search" action into text selection menu

**Example**

https://www.youtube.com/watch?v=4xtEp55MKRE

**Tasks**

- [ ] Define scope: What do we want to trigger from the bubble? Do we need an overlay UI?
- [ ] UX mocks / flow
- [ ] Research: Can we implement an overlay without requesting complicated permissions?
- [ ] Implement bubble overlay
- [ ] Implement overlay UI
- [ ] Trigger search from overlay
- [ ] Add telemetry probes

**Comment by antlam** [comment]
To clarify, we need an experience that allows users (who have set Firefox Focus as the default) to quickly start a search with Firefox Focus after they copy text, from anywhere.

**Comment by brampitoyo** [comment]
Here’s my first attempt at defining a scope:

When you tap-to-copy any kind of text, what the Bubble does will depend on what kind of text you’ve copied.

* If it’s a URL, the bubble should do the equivalent of “Paste & Go”
* If it’s a string of characters, the bubble should do the equivalent of “Paste & Search”

The bubble can look visually identical.

### What do we want to trigger from the bubble? Do we need an overlay UI?

Let’s rephrase the question like so:

> Is there any benefit to showing users a preview of the URL/search page vs. opening the page straight away?

When you’re opening a URL, we can argue that most of the time you’d want to open a webpage. But sometimes, you’re looking for a particular fact or want to check something out quickly. Maybe this is an indication that we should open the webpage in Firefox Focus.

When you’re searching for a keyword, we can argue that you want to eventually get to a webpage, and the search result page is just a means of getting there. I think this is an indication that we should open the search result page in an overlay. When you tap on any item on the search result page, we’ll switch to the full Firefox Focus browser.

So, assuming that we want to treat copied URL and copied URL separately, this is the behaviour I’m proposing:

* If it’s a URL, open Firefox Focus and perform “Paste & Go”.
* If it’s a string of text, perform “Paste & Search” in an overlay. When you tap on any search result, open in Firefox Focus.

### What should the overlay show?

* A quit button (which Android system will give us by default)
* A button to open page in Firefox Focus (in case you want to open that search result page on Firefox Focus – but I think that this is a minority use cases, so this button doesn’t need to be very prominent)

### What might the bubble and overlay look like?

I’m still not quite sure, but here’s my first round of flow and mockup:

![firefox-focus-overlay](https://cloud.githubusercontent.com/assets/51007/26294400/2adb2b2e-3f0f-11e7-913a-a2b58f825674.png)

Thoughts?

**Comment by pocmo** [comment]
Note that this issue is not in our list of P1 (label: v1) or P2 list (label: nice-to-have) for our first release - So at this time we won't implement it. :)

The concept is pretty interesting though :)

**Comment by boek** [comment]
@bbinto @pocmo said that this would be "larger than large". Do we still want to prioritize it?
