### ISSUE TITLE
[meta] Onboarding optimisations

### ISSUE THREAD

**Issue by rtestard** [mozilla-mobile/focus-android#7501]
### Why/User Benefit/User Problem
Optimize new user retention by helping users discover key capabilities that will help them keep using Focus after initial onboarding.

### What / Requirements
We have identified 2 bodies of work to help drive new user retention and engagement through new user onboarding:
    Set to default
    Search Widget

### Acceptance Criteria (how do I know when I’m done?)

- [x] [Update onboarding screen 1](https://github.com/mozilla-mobile/focus-android/issues/7500)
- [x] [Introduce onboarding screen 2](https://github.com/mozilla-mobile/focus-android/issues/7502)     
- [x] [Replace "Go to Settings" CFR with "Start your private browsing session" CFR](https://github.com/mozilla-mobile/focus-android/issues/7503)
- [x] [Update the tracking protection tooltip](https://github.com/mozilla-mobile/focus-android/issues/7504)
- [x] [Update the trash can CFR](https://github.com/mozilla-mobile/focus-android/issues/7505)
- [x] [Introduce an onboarding step to promote widget addition](https://github.com/mozilla-mobile/focus-android/issues/7506)
- [x] [Custom set to default onboarding page for Huawei users ](https://github.com/mozilla-mobile/focus-android/issues/7511)
- [x] [Nimbus support for A/B testing the new onboarding](https://github.com/mozilla-mobile/focus-android/issues/7620)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802647

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
