### ISSUE TITLE
Add to home screen

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#833]
**User Story**

> I want to easily go back to websites I regularly visit in Focus (without ads)

> As a Focus user, I want to easily frequent my favorite website so that I don't have to type in the full-length, same, URL each time

**Tasks**

- [x] UX design / mocks
- [x] ~~Implement additional UI~~ (Not part of the first iteration)
- [x] Add functionality for adding pages to the home screen
- [x] Get a good icon representing the website
- [x] Generate a fallback icon
- [x] Add Telemetry probes
- [x] Add support for new shortcut API in Android O (Requires SDK 26 -> #863)
- [x] Add dialog to update the title of the shortcut
- [x] Finalize strings

**Comment by pocmo** [comment]
@brampitoyo @antlam Do you think this should be an additional menu item? Should we just add the icon to the home screen (like Fennec) does or do we need additional UI to let the user modify the name (like Chrome does)?

**Comment by pocmo** [comment]
For reference: This is the dialog Chrome shows.

![homescreen](https://user-images.githubusercontent.com/89638/27871265-706adf50-61a5-11e7-9e3b-27b8cfe70799.png)

**Comment by antlam** [comment]
For V1, let's keep the additional UI out of it.

**Comment by pocmo** [comment]
> We still want some sort of confirmation UI though!

I was thinking about using the approach we implemented for the "add to home screen" promotion in Fennec: Switching to the home screen - where the user will see the icon appear.

**Comment by pocmo** [comment]
> For V1, let's keep the additional UI out of it.

I'm okay with that. But note that we have been using the page's title in Fennec and sometime this is not the best title for a launcher icon.

**Comment by antlam** [comment]
From my meeting with @pocmo:

Messaging this will be important. It might also be an opportunity to try some stuff and figure out what options we have. For example, "save", "download", "install"? 

@mheubusch thoughts?

**Comment by brampitoyo** [comment]
Adding @antlam because you’ve been meeting with @pocmo about this.

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [I grow tired of entering the URL of a frequently visited website or searching for it each time I use Focus](https://trello.com/c/LeBoSuQM/75-i-grow-tired-of-entering-the-url-of-a-frequently-visited-website-or-searching-for-it-each-time-i-use-focus)

**Comment by antlam** [comment]
iOS issue is issue https://github.com/mozilla-mobile/focus-ios/issues/124

Note: language here is still undecided (Save, Add, etc)

Recent user story proposal: 
> As a Focus user on iOS, I want to easily frequent my favorite website so that I don't have to type in the full-length, same, URL each time.

**Comment by antlam** [comment]
![menu - mdpi - saveadd](https://user-images.githubusercontent.com/1994820/28293068-0ac6c5cc-6b07-11e7-9b00-b2c2af4cb3d1.png)

Essentially what we're talking about ^ (another menu item)

**Comment by pocmo** [comment]
@antlam I landed the first part of this. There's now a menu item and it will add a home screen icon on Android <= 7 (on Android O it doesn't work yet). @ekager is taking this over. For the dialog UI - should we copy what Chrome does or is there anything we should do differently?

**Comment by antlam** [comment]
@pocmo awesome! I was playing with it over the weekend.

Let's start with the pattern we're seeing in Chrome and then improve from there.

**Comment by pocmo** [comment]
I manged to land this without the code to build the actual VIEW intent: Currently shortcuts only open the app and not load a page 🙃 
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/shortcut/HomeScreen.java#L68

**Comment by ekager** [comment]
@antlam you want the dialog to look like Chrome style? With the white background?

**Comment by antlam** [comment]
@ekager that's what I was imagining. 

But since we've adopted a dark theme everywhere else, would it be easier to carry this through here? I think that would look good too!

**Comment by ekager** [comment]
@antlam this is what I currently have with the dark theme. It also sets the cursor at the end of the text and pulls up the keyboard automatically to save the user an extra click. Let me know what changes you would like to see! :) 

<img width="336" alt="screen shot 2017-07-25 at 5 19 32 pm" src="https://user-images.githubusercontent.com/25442310/28599235-b410d986-715d-11e7-83de-dd68daaa0973.png">

**Comment by antlam** [comment]
Leaving a comment here, we've been polishing and finalizing this UX on Slack. New icon PR incoming.

**Comment by mheubusch** [comment]
For the strings, 
the label on the menu  - Add to Home screen (cap H, lowercase s)
the label for the dialog  - Add to Home screen (or Add shortcut to Home screen if there is any reason to think users won't recognize this pattern and need the help)
for the buttons, CANCEL and OK are fine (though ADD might be better) 
Do we need a confirmation message? Or is that replaced by the suggestion to switch to Home and show the shortcut?

**Comment by antlam** [comment]
I don't think we need a confirmation message. The icon shows up on the Home screen and animates in as well.

**Comment by pocmo** [comment]
@ekager I added three new strings to the repo and export: dialog_addtohomescreen_title, dialog_addtohomescreen_action_add, dialog_addtohomescreen_action_cancel. We already had one for the menu item: menu_add_to_home_screen. I just updated the text.

**Comment by bbinto** [comment]
Definitely too late for this release, but I'd love to see what wording does to the usage of this feature, i.e. if we were to change it. to "Save to Homescreen" or "Bookmark to Homescreen".

**Comment by npark-mozilla** [comment]
@pocmo @ekager I was wondering, should the homescreen icon also remember the state of 'Trackers Blocked' switch? (if the user frequents the site that needs TP turned off)

**Comment by pocmo** [comment]
@npark-mozilla Not a requirement for this version. But you could file a new issue for this. :)

**Comment by bbinto** [comment]
Good catch to watch out for in the future.

**Comment by bbinto** [comment]
Positive feedback: https://play.google.com/store/apps/details?id=org.mozilla.klar&reviewId=Z3A6QU9xcFRPRkZGLVp0cjRGSzJiTUxhS0NNUGZseGZvNUtydmljWUpFamJNUVE4bTkyVnZBZkZrSDNxT0hTRnlHQ2pQb3lrNVVLTGJad3RoNFdDbVIwR0Jv

**Comment by Bringoff** [comment]
@pocmo I'm investigating Focus code at the moment and thinking about [HomeScreen](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/shortcut/HomeScreen.java) class. It has different implementations for android API < 26 and 26+. Version for Android prior to Nougat operates with deprecated intent directly. But [ShortcutManagerCompat](https://developer.android.com/reference/android/support/v4/content/pm/ShortcutManagerCompat.html) support library implementation already exists. Are there any reasons Focus doesn't use this?

**Comment by pocmo** [comment]
@Bringoff We have a slightly different behavior (On Android < 26 we switch to the home screen after creating the shortcut). But apart from that no there's no reason. We could switch to ShortcutManagerCompat - If you want to do it file an issue and open a PR. :)

**Comment by huuhaa** [comment]
This doesn't quite fit under this, but kind of still does. Could there be also possibility to add "quick selection" icon of web page to start screen? It might be just me, but I feel it clumsy to open browser, then if you decide to go at some website you already have at home screen (or folder at heme screen), you have to switch browser to background or close it. Then looking the right shortcut from home screen...

I personally would love an option to add 9 quick selection icons at start screen and maybe side swipe for have 9 more (with dots at bottom to show how many and which page you ar at the moment). What do you think?

**Comment by pocmo** [comment]
@huuhaa Please file a new issue for that! Thank you!
