### ISSUE TITLE
[meta] Automate release process

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#862]
For our first release we signed and uploaded APKs manually. We want to automate this for further 
releases.

- [x] Come up with automation plan with release engineering and release management
- [x] Build PRs/Pushes on taskcluster (To avoid surprises when we release)
- [x] #1470 - Get experience in building decision tasks by chunking screenshots
- [x] Create decision task and schedule build pipeline tasks
- [x] #1488 - Build releases on taskcluster
  - [x] Get Adjust token from somewhere
  - [x] Generate versionCode dynamically
- [x] Sign releases on taskcluster
- [x] Upload Nightly builds to the alpha channel on Google Play (on taskcluster)
- [x] Upload Beta builds to the beta chnanel on Google Play
- [x] Figure out how beta builds get into Google Play (promote manually or automated? based on tags?)
- [x] Figure out how release builds get into Google Play (promote manually or automated? based on tags?)
- [ ] #830 Upload releases to archive.mozilla.org

**Comment by pocmo** [comment]
Met with release engineering today. The "Mozilla way" of doing that would be using Taskcluster (like with Fennec). In Taskcluster we could build a pipeline that builds, signs and uploads (to Google Play and archive.mozilla.org) the app.

A minimal setup of this would be to continue building with buddybuild and only sending the build for signing to taskcluster. But even this would be at least a month of work (estimate from release engineering) and the releng team is super busy currently.

Because of that (and because we already have a complex setup with automated tests and external tools like codecov, sputnik) we decided to go forward with the other option: Letting Google Play sign the builds and using an upload key in buddybuild.

To reduce risk (because that's the first time we do that) we want to try this without Focus first. The photon/zerda team wants to use the same meachnism so we let them try first (Both apps are not released and therefore not much can go wrong). In case they are not ready to be our guinea pig in the next week, we are going to publish (not publicly!) our own test app to Google Play (Maybe Focus Beta) to test the whole process. If everything goes as planned we can proceed with using this for Focus. :)

**Comment by pocmo** [comment]
Updated plan after meeting with release engineering and release management: We are going to use taskcluster after all. It gives us the most flexibility and we can keep our secrets secure as well as maintain a continuous change of trust.

However we are not going to replace our existing system. Our test and verify infrastructure with Buddybuild/Travis + External tools is working great. We want to add an additional Taskcluster pipeline that builds, signs and uploads the app (to Google Play AND archive.mozilla.org). This is a bit more work. So we won't have it for the next (at least two) releases.

**Comment by mcomella** [comment]
Some additional notes of small things we should automate, probably after the issues in this bug (file a new bug?):
- Creation of "Releng for [release]" issues
- Creation of "What's new Entry for [release]" issues
- Strictly enforcing "Issue #..."/"Closes #..." tags in github via CI
- Strictly enforcing `qa=y/n` in commit messages via CI and auto-labeling QANotNeeded/ReadyForQA for issues based on it (Susheel in particular wants this)
