### ISSUE TITLE
Automate L10N import

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#929]
_Added by @bbinto_

**Why/User Benefit**
- Improve productivity of Focus team

**What**
- Importing strings into builds of the app automatically

**Acceptance Criteria (how do I know when I’m done?)**

---
I want to automate the L10N import. Exporting strings can still be a manual process (because we want to review the changes). But importing the strings into builds of the app should be automated.

I talked to Stefan and Firefox for iOS seems to do something like this. I want to explore our options here. It shouldn't make it super hard for regular developers to get other locales in their local builds (like Fennec).

## Tasks

- [x] Make L10N scripts for import etc. independent from gradle (to run them in automation etc.)
- [x] Modify docker image to support importing of translations in automation (a2po dependencies)
- [ ] Import strings automatically when creating screenshots on taskcluster (see #980)
- [x] Keep a list of "release" locales in the repository and only import those for release builds
- [ ] (Maybe) remove translations from the repository, because they are imported at build time
- [ ] (Maybe) run check_translations.py in automation so that we can find issues with translated strings

Release builds should only contain the defined locales. All other builds can include all available locales.

**Comment by pocmo** [comment]
Closing: This is half automated and the L10N team is working on making their tools support Android projects.
