### ISSUE TITLE
Use Photon color palette

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#939]
Filing so I don't forget....

**Update:**
- [x] Toolbar gradient (#A01142 #90116D #5C1166)
- [x] Toolbar inactive (#453440 #433446 #3B3445)
- [x] Home view gradient, Same as Toolbar gradient (#A01142 #90116D #5C1166) 
- [x] Text (white and black - #272727)
- [x] Circular and sheet FAB button (#B5007F)
- [x] ^ pressed state (#7D004F)
- [x] Sheet list (#F9F9FA)
- [x] ^ pressed state (#EDEDF0)
- [x] Multitasking FAB button (#0A84FF)
- [x] ^ pressed state (#0060df)
- [x] URL text highlight (#B5007F)
- [x] Theme accent color, cursor and handles (#B5007F)
- [x] Blue 50 for Settings (#0A84FF)
- [x] Purple switch, on dialogs (#9400FF) 
- [x] Black overlay 80% (#CC000000)
- [x] URL bar 20% (#33FFFFFF)
- [x] Search or enter address placeholder text 50% (#80FFFFFF)

See issue #1260 for dialogs

**Comment by pocmo** [comment]
FYI: Almost all colors we currently use should be in here:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/values/colors.xml

**Comment by antlam** [comment]
![screen shot 2017-09-05 at 10 45 30 am](https://user-images.githubusercontent.com/1994820/30074715-5f7b6306-9227-11e7-92bc-3e9f0f11d89c.png)

WIP preview of before v. after

**Comment by antlam** [comment]
This is going in iOS during Ebony, perhaps we could aim for Ebony too?

**Comment by pocmo** [comment]
>  Purple switch, on dialogs (#9400FF)

For now we are using the accent color (#B5007F) here - All controls pick this up automatically.

**Comment by pocmo** [comment]
![cursor](https://user-images.githubusercontent.com/89638/30475745-29a72c72-9a08-11e7-92c9-6dd145cac392.png)

^-- On my device it's pretty hard to see the cursor here. I was tapping the field to make the cursor appear multiple times and thought the app froze.

**Comment by pocmo** [comment]
@antlam --^

**Comment by antlam** [comment]
@pocmo could we make the cursor white? #FFFFFF

**Comment by pocmo** [comment]
![cursor-white](https://user-images.githubusercontent.com/89638/30495140-193b7274-9a4b-11e7-9c5b-e18fd4d4888a.png)

Better. But maybe a bit too strong? Maybe make it transparent?

**Comment by antlam** [comment]
I think it's fine :)

**Comment by pocmo** [comment]
![cursorwithalpha](https://user-images.githubusercontent.com/89638/30496602-33e131c2-9a50-11e7-9896-197eb34f7a8d.png)

This would be 80% (#ccffffff).

**Comment by antlam** [comment]
Nice! I'll update our design file too

**Comment by pocmo** [comment]
@antlam I updated all colors now. The last thing on the list is the switch: Did we decide whether we want to use purple here or keep the accent color?

**Comment by antlam** [comment]
@pocmo let's keep the accent color, I think it works. I can update the design files too.

This is just for the menu
