### ISSUE TITLE
Multitasking within Focus, switching between sites

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#960]
### Tasks

* [x] Finalize UX spec
* [x] Land strings so that L10N team can translate them
* [x] Refactor app architecture to support multiple sessions
* [x] Implement new Floating Action Button UI for opening and switching between tabs
* [x] Add option to open a new tab to the context menu
* [x] Add telemetry probes for all actions
* [x] Verify whether we need additional telemetry (Number of tabs per session?)
* [x] Testing: Do we still send all telemetry correctly?
* [x] Testing: Custom tabs and other edge cases (Share to Focus, First run etc.)

### Follow-up bugs

* #1230 - In new tab, trackers blocked setting is not remembered upon revisiting.
* #1231 - New tab shows more than first subdomain

**Comment by pocmo** [comment]
See also: #751 - Support for tabs.

**Comment by antlam** [comment]
There's a lot to do for 2.0 already. I think this is going to be one of the larger UX efforts (to get right at that) and I might suggest pushing this to after.

**Comment by bbinto** [comment]
We agreed to move this to the next major update (3.x)

**Comment by andreicristianpetcu** [comment]
Please stick with tabs for the multitasking aspect. Please do not invent a new UX concept just for this. Tabs are awesome. Thank you!

**Comment by antlam** [comment]
Thanks @andreicristianpetcu 

Could you share some more helpful insight into what you most often use tabs for (on mobile) exactly?

**Comment by TruboXL** [comment]
While not exactly a use case for tabs, I have been viewing certain websites that requires pop-ups.

Without tabs, websites just redirect to the ads (instead of opening up another tab/window) and it is sometimes impossible to advance to the next page of the intended website when you Go Back.

**Comment by andreicristianpetcu** [comment]
@antlam I am a heavy reddit user and most of my browsing is on Reddit or starts from there. I usually start several tabs in parallel from various bookmarks. I have named bookmarks for [refi](https://www.reddit.com/r/firefox/new/) (Reddit Firefox), [remo](https://www.reddit.com/r/mozilla/new/) Reddit Mozilla or [rena](https://www.reddit.com/r/worldnews+europe+news+politics+live) (Reddit News All). Since Reddit loads slow, I open several tabs and wait for them to load.

I either open them by typing the name of the bookmark in the URL or I just click on the Activity Stream pinned items if it is on the list. If I find something interesting I open a new tab with that Reddit post.

Forgot to mention: I use Firefox Nightly for this workflow and I would like to replicate it on Firefox Focus.

Does this help? Do you want a video? :D

**Comment by bbinto** [comment]
@antlam friendly reminder to add the mocks here :)

**Comment by antlam** [comment]
As @pocmo is continuing to figure out the plumbing here, here's an update of the latest. Finalized flow and specs to follow.

Top row: non-collapsed FAB
Second row: collapsed FAB

<img width="905" alt="screen shot 2017-08-04 at 5 07 05 pm" src="https://user-images.githubusercontent.com/1994820/28990975-7573f960-7937-11e7-96ca-3ef1f7e60450.png">

**Comment by andreicristianpetcu** [comment]
I think it is better to use the title of the page instead of the hostname as a tab identifier. You might have several tabs for the same web site. This is how Fennec does it now. Consistency would be nice :)

**Comment by antlam** [comment]
Thanks @andreicristianpetcu ! When I was designing the tabs tray on Fennec, it made sense for us to use page titles. But we'll have to figure what works best in this case. We'll be sure to iterate and improve on this as we go.

**Comment by antlam** [comment]
Attaching V1 designs

![flow_temporarytabs1](https://user-images.githubusercontent.com/1994820/29158928-6f25a908-7ddf-11e7-8051-204f1e787e9c.png)

**Additional notes for context**
- let's look at this as the first step of a multi-step, iterative design process. 
- the goal is to move us towards a better default browser experience, but not necessarily replicate Firefox/Fennec's features 
- A typical flow of a Focus user currently ends with Erase (Browse. Erase. Repeat.)
- From telemetry, we know that there is a 50/50 split between users erasing with the FAB vs the notification
- There are still some details that we can nuance further, like copy, iconography, edge cases, etc

**Things to consider**
- Comparatively, how well (or not) does this help users in shopping and banking use cases?
- How might we continue layering on top of this idea in subsequent versions?
- With our new Add to Home screen feature, how do users leverage/adapt these to solve their use cases?

**Comment by bbinto** [comment]
@antlam thanks, still missing in this issue is
- how many tabs one user can open
- what happens if user reached max tabs and tries to open another one coming from another app
 
(basically, all we've talked about in our slack chat, would be great to have this listed/outlined in the specs doc as well)

**Comment by mheubusch** [comment]
My recommended instructional copy is "Open temporary tab" - think "open" is better than "add".

**Comment by antlam** [comment]
@bbinto good point! And @pocmo also raised those issues too. We'll continue to update this.

# of Temporary tabs, I'd suggest starting with a max of 6:
- There are a few written articles on the web that suggests this is approx. equivalent to the mental capacity of a user when using the web to perform a specific task
- I think I remember we saw a similar pattern in Firefox re: the number of tabs people kept open (obviously there were very few people leaving 99 tabs open)
- 6 tabs (give or take 1 or 2) seems like a sensible amount to help in a "comparison shopping" use case 
- the design guidelines for the FAB component max out at 6 items. 

what happens if user reached max tabs:
- we were going to simply disable the option if the max has been reached. But I just got an idea. will post updates today!

Side note:
- we should also measure this to see what the distribution looks like for users per session. I.e. how many Temporary tabs do most users open when performing a task in Focus?

**Comment by brampitoyo** [comment]
Below is a just-finished specs for multitasking that @antlam and I have been working on today. Although it doesn’t reflect our final visual design (which will be posted later on), it should be the source of truth for interaction design and flow.

![spec multitasking](https://user-images.githubusercontent.com/51007/29211383-6da0c274-7ecb-11e7-94aa-2a822858b348.png)

**Comment by pocmo** [comment]
Thanks! That's a great spec. :)

@mheubusch @antlam @brampitoyo I added a list of strings I think we need to the first comment. Please have a look.

**Comment by mheubusch** [comment]
Thanks for listing the strings, @pocmo -  here are my recommendations: 

Accessibility string for the new floating action button (FAB): Expand
Label for the FAB: Erase browsing history
Accessibility string for the "+" button: Open tab
Accessibility string for the "X" button when typing new tab's address: Close tab  
Context menu entry: Open link in new tab
Dialog title: Open link in selected tab
Dialog action: OPEN
Dialog action: CANCEL

(@antlam : I've been playing with messaging to explain the 5-tab limit, but am thinking we should go with what i have and if we can test or get feedback about needing this to be clearer I can revisit.  Also, I removed reference to "temporary" in the tabs - while they are not always visible, they are persisting in the background and i don't want to mislead.  if we find that people expect tabs to have tabbed browsing, we can consider something like floating tabs or tab-less tabs, but for now wanted to keep things simple. )

**Comment by jbreckmckye** [comment]
Please don't do this.

I will probably be alone in urging you to stick with the single tab model. But I seriously believe it's focus' best feature.

I downloaded this browser to avoid adverts and tracking. But I kept using it because it changed the way I browsed. I used to have real trouble controlling my browsing habits: I would never stick to my original task, but open up scores of tabs as my curiosity would get the better of me. Oh, what about this topic? Hmm, that makes me want to search for that. Oh, I shall have to read that link later. And before I knew it I'd spent an hour on the internet, laid on the sofa, having _done_ absolutely nothing.

Focus changed that: it keeps me _focused_ on a single task. When the task ends, I might start another one, a new search or an article, but only if I remember and only if I still care enough to bother looking it up.

The effect is transformative. It puts me back in control. It makes me feel like I'm the one controlling the browsing, not some website's psychological trickery or an algorithm's UX dark patterns.

Focus works well because it is the simplest and least distracting browser for Android that isn't technologically crippled. The search-read-restart-repeat flow puts me in the habit of destroying my browser data as soon as possible. And the fact I finish pages with nowhere to go puts me back in control of my free time. Please keep the focus in Firefox Focus.

**Comment by xrxrxr** [comment]
Or can add in settings
multiple tabs options who is activated by default
With the label that it can break some webpages if is desactivated

**Comment by bbinto** [comment]
@brampitoyo your spec doc is amazing, so helpful, and thanks for addressing pretty much all of my concerns/questions.

@antlam's comment:
> we should also measure this to see what the distribution looks like for users per session. I.e. how many Temporary tabs do most users open when performing a task in Focus?

I assume @pocmo will add telemetry so we can have a nice histogram for analysis.

In general, I believe once we have a first working implementation in the product, we will be able to test it out and "feel" it and address anything we might have missed...can't wait!

**Comment by pocmo** [comment]
@jbreckmckye Thank you for your comment. You are definitely not alone with that. There have been a lot of discussions around if and how we should support multitasking. If you look at our current spec you will see that we won't introduce management of single tabs in a session and limit the number of total concurrent tabs. Hopefully this will still support your use case of a limited *focused* browsing session.

**Comment by pocmo** [comment]
@antlam @brampitoyo Can you mock how this screen should look like once the user starts typing?

![image](https://user-images.githubusercontent.com/89638/29355380-2299f468-8271-11e7-94ed-5905cfda7ee0.png)

**Comment by pocmo** [comment]
@antlam @brampitoyo Per guidelines I think this dialog doesn't require any actions. Compare with our dialog to select a new default search engine.

![image](https://user-images.githubusercontent.com/89638/29355483-80aca384-8271-11e7-8bb8-8a1926b1d241.png)

**Comment by antlam** [comment]
> @antlam @brampitoyo Per guidelines I think this dialog doesn't require any actions (replace/cancel). Compare with our dialog to select a new default search engine.

We might not need that dialog anymore if we're away from the "mini expanded FAB bubbles" UI.

Here's what I've been going with recently in terms of visual design: the expanded sheet.

![screen shot 2017-08-18 at 4 07 45 pm](https://user-images.githubusercontent.com/1994820/29480735-64b4bcba-842f-11e7-814a-88272f274215.png)

**Comment by bbinto** [comment]
@pocmo trying to understand if there are more strings needed as you added the label "needs strings" back

**Comment by pocmo** [comment]
Yeah, I think we might need new strings for the sheet above ("Erase everything in your World") and  maybe for the tab counter floating button (for accessibility only).

**Comment by mheubusch** [comment]
@bbinto since erasing is an all or nothing thing, (ie you can only erase or not erase, you cannot erase only 1 tab at a time) my recommendation for the button is: Erase browsing history

The a11y string should be: Tabs open: <#>

**Comment by mheubusch** [comment]
@lime124 am also sharing a design comp @antlam shared with me - not sure if we need other design elements (like a close button or X on each tab's line in the multitasking menu or if you can't close them one at a time. 
<img width="580" alt="screen shot 2017-08-17 at 11 35 37 pm" src="https://user-images.githubusercontent.com/20115914/29689549-363e8f8c-88e9-11e7-869a-0a0a3b668c7a.png">

**Comment by antlam** [comment]
> not sure if we need other design elements (like a close button or X on each tab's line in the multitasking menu or if you can't close them one at a time.

I'll post finalized visual specs later but I don't think we need a close button or an X on each tab's line since we aren't supporting single-close in the first iteration

**Comment by Benestar** [comment]
Wouldn't it make more sense to show the blue `<>` button (as in the previous mockup) when not expanded and the garbage bin only in the expanded menu? In my opinion the additional tab count button adds too much clutter to the page if it is expanded by default.

For closing tabs, maybe we can just swipe them away in the expanded sheet?

**Comment by brampitoyo** [comment]
I’ve updated my multitasking specs with the latest round of UI that @antlam had designed. The spec reflects the decisions made at the meeting we’ve just had, and should represent the latest design.

**Comment by pocmo** [comment]
Telemetry probes are documented in the wiki. I added additional events for opening new tabs and actions that can be performed in the tabs tray. Additionally open and erase events (also already existing!) will report the position of the currently selected tab and the total number of tabs as telemetry extras.

**Comment by pocmo** [comment]
I'll close this bug (all tasks are done) and file follow-up bugs for additional work that might be needed (to have separate discussions; No-Jun already filed some too).

**Comment by bbinto** [comment]
> I’ve updated my multitasking specs with the latest round of UI that @antlam had designed. The spec reflects the decisions made at the meeting we’ve just had, and should represent the latest design.

Thanks @brampitoyo ...where can I find them?

@pocmo just reviewed the Telemetry wiki, and <3 it. Thanks

**Comment by antlam** [comment]
Logging conversations from various threads here:

V1, unlimited number of tabs for now, monitor histogram
V2, revisit and refine purpose of multitasking using tabs/other means #1248
