### ISSUE TITLE
[meta] Automate screenshots

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#980]
As soon as we auto-import translations (#929) it would make sense automating the screenshot process too.

The iOS team wants this too - so let's join forces!

## Tasks ##
- [x] Proof of concept
- [x] Modify docker image to support taking screenshots (emulator, fastlane, image tools)
- [x] Test execution on taskcluster
- [x] Run complete screenshot test suite
- [x] Resize and minify screenshots
- [ ] Stabelize UI test
- [x] Split task into multiple tasks (decision task)
- [ ] Upload screenshots

**Comment by pocmo** [comment]
@npark-mozilla FYI! You probably know best what we would need for that. :)

**Comment by npark-mozilla** [comment]
Hmm, it is matter of running series of following commands:
export LC_ALL="en_US.UTF-8"
./gradlew assembleDebug assembleAndroidTest
fastlane screengrab run  (need to install fastlane and screengrab beforehand)

<then copy the screenshot folder to my github repo>

BUT, this entails that we run it on an actual device, and BB real devices seem pretty finicky... we'll find out
maybe we can put this on buddybuild_postbuild.sh or something like that? (depends on how we automate l10n import)

**Comment by pocmo** [comment]
The iOS team was thinking about planting a machine in some office. Maybe we could just attach an Android phone to it? But from past experience: This often has issues for random reasons. :)

**Comment by pocmo** [comment]
Notes from our meeting:
 * https://public.etherpad-mozilla.org/p/focus-screenshots-automation
 * https://pastebin.mozilla.org/9032481

**Comment by ekager** [comment]
Can we close this meta?

**Comment by npark-mozilla** [comment]
This was complicated by having older sim running on taskcluster and having intermittent failures - it's not done, but it seems unclear that we'll be working on this.  @pocmo , thoughts?

**Comment by pocmo** [comment]
I talked to the L10N team some time ago and it is likely that they are going to own the screenshot automation for our apps.

I definitely won't be able to work on that.

**Comment by npark-mozilla** [comment]
Okay let's close this issue then.
